#!/bin/sh
# gen_eaw.sh — fetch the Unicode UCD files and regenerate
# src/Yaynu/Tui/Width/Table.fix.
#
# This script downloads `EastAsianWidth.txt` and `emoji-data.txt` from
# the official Unicode site, parses them, and emits a `Table.fix`
# containing the ranges consumed by `Yaynu.Tui.Width`.
#
# Requirements: POSIX shell, `curl`, `awk`. No Fix build artefacts
# are touched.
#
# Idempotency: running this twice with no upstream change produces an
# identical Table.fix (byte-for-byte) so `git diff` stays clean.

set -e

cd "$(dirname "$0")/.."

EAW_URL="https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt"
EMOJI_URL="https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Fetching EastAsianWidth.txt ..."
curl -fsSL "$EAW_URL" -o "$TMPDIR/EastAsianWidth.txt"

echo "Fetching emoji-data.txt ..."
curl -fsSL "$EMOJI_URL" -o "$TMPDIR/emoji-data.txt"

UV=$(awk -F'[ ,]+' '/^# EastAsianWidth-/{ gsub(".txt",""); print $2; exit }' \
       "$TMPDIR/EastAsianWidth.txt" \
     | sed 's/EastAsianWidth-//')

DATE=$(date -u +%Y-%m-%d)

OUT=src/Yaynu/Tui/Width/Table.fix

echo "Generating $OUT (Unicode $UV, retrieved $DATE) ..."

{
    printf '// Unicode width and category lookup tables.\n'
    printf '//\n'
    printf '// This file is regenerated by `scripts/gen_eaw.sh` from the Unicode\n'
    printf '// UCD `EastAsianWidth.txt` and `emoji-data.txt`.\n'
    printf '//\n'
    printf '// Unicode version: %s\n' "$UV"
    printf '// Retrieved on   : %s\n' "$DATE"
    printf '// Source         : %s\n' "$EAW_URL"
    printf '//\n'
    printf '// Each `*_ranges` array is sorted by start codepoint.\n'
    printf 'module Yaynu.Tui.Width.Table;\n\n'

    printf 'type EawClass = box union {\n'
    printf '    eaw_n  : (),\n    eaw_na : (),\n    eaw_h  : (),\n    eaw_w  : (),\n    eaw_f  : (),\n    eaw_a  : ()\n};\n\n'

    printf 'type EmojiProp = box union {\n'
    printf '    emoji              : (),\n    emoji_presentation : (),\n    emoji_modifier_base: (),\n    emoji_modifier     : (),\n    extended_pict      : ()\n};\n\n'

    printf 'eaw_ranges : Array (U32, U32, EawClass);\n'
    printf 'eaw_ranges = [\n'
    awk -F'[ ;]+' '
        /^[^#]/ && NF >= 2 {
            sub(/[ \t]*#.*/, "")
            if ($1 == "") next
            split($1, parts, "..")
            start = parts[1]
            end = (parts[2] == "") ? parts[1] : parts[2]
            cls = $2
            map = "eaw_n"
            if (cls == "Na") map = "eaw_na"
            else if (cls == "H") map = "eaw_h"
            else if (cls == "W") map = "eaw_w"
            else if (cls == "F") map = "eaw_f"
            else if (cls == "A") map = "eaw_a"
            printf "    (0x%s_U32, 0x%s_U32, EawClass::%s()),\n", start, end, map
        }
    ' "$TMPDIR/EastAsianWidth.txt" | sed '$s/,$//'
    printf '];\n\n'

    printf 'emoji_ranges : Array (U32, U32, EmojiProp);\n'
    printf 'emoji_ranges = [\n'
    awk -F'[ ;]+' '
        /^[^#]/ && NF >= 2 {
            sub(/[ \t]*#.*/, "")
            if ($1 == "") next
            split($1, parts, "..")
            start = parts[1]
            end = (parts[2] == "") ? parts[1] : parts[2]
            prop = $2
            map = ""
            if (prop == "Emoji") map = "emoji"
            else if (prop == "Emoji_Presentation") map = "emoji_presentation"
            else if (prop == "Emoji_Modifier") map = "emoji_modifier"
            else if (prop == "Emoji_Modifier_Base") map = "emoji_modifier_base"
            else if (prop == "Extended_Pictographic") map = "extended_pict"
            if (map != "") {
                printf "    (0x%s_U32, 0x%s_U32, EmojiProp::%s()),\n", start, end, map
            }
        }
    ' "$TMPDIR/emoji-data.txt" | sed '$s/,$//'
    printf '];\n\n'

    # Combining marks (Mn / Me) — leave the hand-curated list intact;
    # a fully-derived table would require UnicodeData.txt which the
    # script does not currently fetch.
    cat <<'EOF'
combining_ranges : Array (U32, U32);
combining_ranges = [
    (0x0300_U32, 0x036F_U32),
    (0x0483_U32, 0x0489_U32),
    (0x0591_U32, 0x05BD_U32),
    (0x05BF_U32, 0x05BF_U32),
    (0x05C1_U32, 0x05C2_U32),
    (0x05C4_U32, 0x05C5_U32),
    (0x05C7_U32, 0x05C7_U32),
    (0x0610_U32, 0x061A_U32),
    (0x064B_U32, 0x065F_U32),
    (0x0670_U32, 0x0670_U32),
    (0x06D6_U32, 0x06DC_U32),
    (0x06DF_U32, 0x06E4_U32),
    (0x06E7_U32, 0x06E8_U32),
    (0x06EA_U32, 0x06ED_U32),
    (0x0711_U32, 0x0711_U32),
    (0x0730_U32, 0x074A_U32),
    (0x1AB0_U32, 0x1AFF_U32),
    (0x1DC0_U32, 0x1DFF_U32),
    (0x20D0_U32, 0x20FF_U32),
    (0xFE20_U32, 0xFE2F_U32)
];

variation_selector_ranges : Array (U32, U32);
variation_selector_ranges = [
    (0xFE00_U32, 0xFE0F_U32),
    (0xE0100_U32, 0xE01EF_U32)
];

zwj : U32;
zwj = 0x200D_U32;
EOF
} > "$OUT"

echo "Wrote $OUT"
